LOM-449: change privacy policy logic
City-of-Helsinki/drupal-helfi-form-tool pull request #163
Opened 2023-03-24 11:32 UTC by suvikankare

# [LOM-449](https://helsinkisolutionoffice.atlassian.net/browse/LOM-449)

## What was done

* Added conditional privacy policy link

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/LOM-449-privacy-policy`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that when selected Peruskoulu or 10lk, you see perusopetus-privacy policy and when selected lukio you see lukio-privacy policy

2023-03-27 05:35 UTC, jiisuominen requested changes
![image](https://user-images.githubusercontent.com/892920/227849656-07d94add-3bfe-4297-a038-40bbc8dc7129.png)

![image](https://user-images.githubusercontent.com/892920/227849712-8713ff07-e93a-45ac-a479-8348155ce109.png)

Toi täppäys ei jotenki mee oikein.

Plus tsekkaa Petriltä tuon toteutuksen saavutettavuus kun dynaamisesti vaihdetaan elementtejä.

2023-03-27 08:48 UTC, strangeworlder reviewed
Noihin rekisteriselosteisiin vois laittaa visuaalisen indikaation (tähden), että ne on pakollisia. Erroria ne pukkaa jos ei oo tehnyt oikein, mutta se asteriski ilmoittamassa pakollisuutta vois olla ihan hyvä lisä

2023-03-27 14:43 UTC, strangeworlder approved these changes

2023-03-28 05:06 UTC, jiisuominen approved these changes

2023-03-28 05:07 UTC, merged